### ISSUE TITLE
[tutorial] UINT8 quantization inference example

### ISSUE THREAD

**Issue by tpoisonooo** [dmlc/tvm#1209]
I have converted tensorflow quantization model into onnx.

Referring [Compile ONNX Models tutorial](http://docs.tvm.ai/tutorials/nnvm/from_onnx.html#sphx-glr-tutorials-nnvm-from-onnx-py), I got runtime error:
`NotImplementedError: Operator FakeQuantWithMinMaxVars not implemented`

I have read [this quantization inference paper](https://arxiv.org/abs/1712.05877), is that means I have to  implement FakeQuantWithMinMaxVars operator byself?

Would you please give a UINT8 quantization example?

**Comment by tqchen** [comment]
please use https://discuss.tvm.ai/ for general discussions, the support for int8 inference is work in progress and we will put out more resources in next release cycle

**Comment by ghostplant** [comment]
@tqchen Is UINT8 quantization supported now? I also uses that BBS but hardly get any answers. Thanks!

**Comment by WeberChen** [comment]
Hi @tqchen 

Because I need to import the pre-quantized model from Tensorflow but not from TF-lite, I need the FakeQuantWithMinMaxVars operator for the following steps.

Therefore, the issue-706 in "discuss.tvm.ai" may not be suitable for me
https://discuss.tvm.apache.org/t/tensorflow-operator-fakequantwithminmaxvars-not-implemented/706

Would you please put out more resources about the FakeQuantWithMinMaxVars?

or Could you tell me how to build/implement the non-existed op by myself?

Thanks
