### ISSUE TITLE
TVM can't run with static c runtime (/MT) on Windows due to std:: string in dll interface

### ISSUE THREAD

**Issue by souptc** [dmlc/tvm#1582]
Currently if we build tvm with static runtime (/MT) option on Windows, tvm will crash due to the std::string in dll interface, like:

`TVM_DLL Tensor placeholder(Array<Expr> shape,
                           Type dtype = Float(32),
                           std::string name = "placeholder");`

basically on windows it is not a good practice to have object type like std::string in dll interface, if build with /MT option, you will hit the crash that when invoke this function, because the "name" object is constructed in caller's C runtime, but hit deconstruction in tvm's C runtime.

A better solution is to use const char* in the shared library interface instead of std::string.

**Comment by tqchen** [comment]
This problem is better suited to be in https://discuss.tvm.ai/. This is indeed a problem that will happen for every C++ project that have dll boundary and tries to statically link libc++(which results in different allocator). Similar things will happen for things like std::vector etc.

In my experience, it is really hard to get such things right in c++, the best way is to resort to C API, which most of our language wrapper do, or not doing static linking.
