### ISSUE TITLE
_convert_convolution in NNVM from_keras has a fatal error of calculation of dilation rate and not inserting ZEROS in the weight list after editing the kernel_h kernel_w

### ISSUE THREAD

**Issue by moemen95** [dmlc/tvm#1713]
PLEASE look at this function again and fix the dilation rate calculation and don't forget to insert zeros in the Weightlist.

**Comment by moemen95** [comment]
Operator conv2d(channels=64, kernel_size=[3, 5], padding=[0, 0], dilation=[1, 2], strides=[1, 1], use_bias=True, name=conv2d2) expects weight's shape to be [64,32,3,5], but got [64,32,3,3]

**Comment by Huyuwei** [comment]
Thanks for reporting this. It should be fixed by #1715 

The weight shape of dilated conv passed from frontend to nnvm compiler should be the original h and w, not including inserted zeros. NNVM supports dilated conv by inserting a dilate op: https://github.com/dmlc/tvm/blob/master/nnvm/python/nnvm/top/nn.py#L94-L102
