### ISSUE TITLE
[TESTS] Add ONNX frontend test for CPU into CI

### ISSUE THREAD

**Issue by yongwww** [dmlc/tvm#1864]
Got "4 failed" when tried to run tvm/nnvm/tests/python/frontend/tensorflow/test_forward.py on Mac, the related test cases are test_forward_reduce, test_forward_inception_v1, test_forward_mean and test_forward_rel_ops.

I checked the tvm CI (http://ci.tvm.ai:8080/blue/organizations/jenkins/tvm/activity/) and didn't find the onnx frontend test is included for CPU machine.

**Comment by wweic** [comment]
`test_forward_reduce` and `test_forward_reduce` are failed because `TOPI_REDUCE_ATLEAST1D` is 0:
https://github.com/dmlc/tvm/blob/44df04a1ef1d0f6dd36b0863695e5ea021d9d759/topi/include/topi/reduction.h#L27-L29

so that `MakeReduceTargetShape` deduced empty shape for reduction op that reduces on all axes:
https://github.com/dmlc/tvm/blob/44df04a1ef1d0f6dd36b0863695e5ea021d9d759/topi/include/topi/reduction.h#L107-L109

I think we should always set `TOPI_REDUCE_ATLEAST1D` to 1? @tqchen

**Comment by tqchen** [comment]
TOPI TOPI_REDUCE_ATLEAST1D is set to 0 because it is compatible with numpy convention and we decide to force new code(relay(nnvmv2)) toward that direction, we will need to fix the other part of the code(likely the testcases)

**Comment by tqchen** [comment]
close this for now, future onnx test cases will be added for relay
