### ISSUE TITLE
Question about split op in get output number code.

### ISSUE THREAD

**Issue by BobLiu20** [dmlc/tvm#2037]
see codes:
https://github.com/dmlc/tvm/blob/b840e9602e357c50124d0c7fb131c52321062570/nnvm/src/top/tensor/transform.cc#L394

why output number = param.indices_or_sections.ndim() + 1 but not param.indices_or_sections.ndim() ?

Since I using import onnx to tvm. The split op is encounter error: output number incorrect.
for example:
indices_or_sections = [2, 2, 1]
it's mean that output number is 3.
anybody help me?  Thanks.

**Comment by srkreddy1238** [comment]
This look like a bug in onnx frontend.

NNVM expects indices as an ascending ordered list which indicates the indices to split with start as 0 and end as length of dimension, hence the ```+1```.
In ONNX the ```split``` arg indicates the length of splits instead of indices.

You are welcome to contribute a fix for this.

**Comment by tqchen** [comment]
Thanks, @BobLiu20 @srkreddy1238 1
