### ISSUE TITLE
[DOCS] Devguide: TVM Codebase Walkthrough Tutorial

### ISSUE THREAD

**Issue by tqchen** [dmlc/tvm#2160]
As more contributors start to collaborate on TVM, it would be super helpful to write a few developer guides to walk through the TVM code base. As an open source project, we value the maintainability and docs above the code itself, and we should provide some dev guide to do so.  The current runtime system doc is one example. But we need more of these.

In particular, it would be helpful to analysis a simple example (e.g., vector add, or relay compilation) and go through all the files/steps it involved. Because we have the PackedFunc and sometimes code goes across python/c++, such an initial navigation example would be super helpful for beginners who want to work on the codebase.  Please reply to this issue if you are interested in helping out on this.

## Proposed Action Item
Let us build a dev-guide series called hacking TVM by example. The general idea is to provide a simple python side example and walk through the details, when necessary, we can focus on a particular part of detail and leave others into other examples. This kinda of example is usually complementary to the general document we have so far to highlight certain problems a developer might have.

Some of the existing resources:
- https://docs.tvm.ai/tutorials/dev/low_level_custom_pass.html#sphx-glr-tutorials-dev-low-level-custom-pass-py
- https://docs.tvm.ai/dev/runtime.html

We can propose new items, for example, one action item could be what happens when we build an add one function in CUDA and LLVM

**Comment by masahi** [comment]
I want to contribute some write-up, since this issue is kind of dear to my heart. I can kick-start with a vector-add example, if nobody is going to do it. Recently I've studied how exactly python and c++ interop works (without using pybind or Boost Python etc). It would be interesting to write about it too.

Below are things which I think should be documented:
* How to add a new backend. Recently I was asked about this, but I couldn't point to a relevant document. 
* How the TOPI target dispatching mechanism works

Below are things I'm not familiar with. I appreciate if somebody can write about them.
* Relay IR design, compilation mechanism etc. How it relates to traditional computational graph representation. (They are discussed on Github, but not documented.)
* TVM IR lowering process. How an initial Realize/Provide stuff gets transformed into a low level IR. How bounds inference works.

**Comment by tqchen** [comment]
Thanks for @Ravenwater @masahi this all makes sense and please go for it. For specific details, I would recommend us to open new threads(like working threads) in the discuss, where everyone can jump in and add details.

**Comment by Ravenwater** [comment]
Ok, started this thread: https://discuss.tvm.ai/t/tvm-vta-architecture-scope-and-roadmap/1212

**Comment by tqchen** [comment]
#2273 thanks to @masahi

**Comment by FrozenGene** [comment]
Ah...I think I can take one. As @tqchen know, I am writing articles to introduce TVM to Chinese readers and wish to attract them to join us (see https://zhuanlan.zhihu.com/p/50529704) . My next article will be introduce one op of frozen model (like CoreML, Keras and so on) , then how to change into NNVM (Relay doesn't have frontend and I don't also be familiar with that， sorry about this), then how to called into TVM, then how to become LLVM IR. If @tqchen think this way (top -> down)  is also good, I will PR this go-through tutorial when I complete this Chinese version.
