### ISSUE TITLE
[BUG][LLVM] Division by inf bug (affects sigmoid)

### ISSUE THREAD

**Issue by sgrechanik-h** [dmlc/tvm#2421]
The commit 194a2e7cfd4b4b4a702e081fdf098377fa5a6a66 (#2386) introduced the following bug: in some cases sigmoid returns NaN instead of 0. The reason is that llvm started to compute reciprocals using the instruction `rccps` instead of `divs`, however `rccps` seems to work incorrectly when the argument is `inf`, returning nan instead of 0. The bug can be demonstrated by the following code:
```python
import tvm
import topi
import numpy as np

def get_shape(tensor):
    return [tvm.ir_pass.Simplify(s).value for s in tensor.shape]

n = 4

A = tvm.placeholder((n,), name='A')

B = tvm.compute((n,), lambda i: 1.0/(1e+37*A[i]), name='B')

sout = tvm.create_schedule(B.op)
mout = tvm.build(sout, [B, A])

print(mout.get_source('asm'))
print()

aaa = [tvm.nd.array(np.zeros(get_shape(B), 'float32')),
       tvm.nd.array(np.full(get_shape(A), 100, 'float32'))]
mout(*aaa)
print(aaa[0].asnumpy())
```
The result is `[0. 0. 0. 0.]` before the commit and `[nan nan nan nan]` after the commit.

One of the solutions is to disable `UnsafeFPMath` in `llvm_common.cc`. In this case the bug disappears and the code still gets vectorized. (Also I think we should consider disabling NoInfsFPMath and NoNaNsFPMath as well.)

**Comment by denis0x0D** [comment]
By the way, here is a discussion about reciprocal instruction accuracy and performance https://bugs.llvm.org/show_bug.cgi?id=21385

We also, probably, can disable it for kernel function by using attributes 
`llvm_function->addFnAttr("reciprocal-estimates", "!sqrtf, !vec-sqrtf, !difv, !vec-divf")`
 since this is checking at
https://github.com/llvm-mirror/llvm/blob/master/lib/CodeGen/TargetLoweringBase.cpp#L1689
But, I'm not sure it would work for all llvm version, because those flags were moved from TargetMachine to Lowering somehow.
