### ISSUE TITLE
Windows NNVM Module export_library error

### ISSUE THREAD

**Issue by chinakook** [dmlc/tvm#2450]
```
Traceback (most recent call last):
  File "deploy_ssd_tvm.py", line 40, in <module>
    lib.export_library("./deployed_model/deploy_lib.dll", fcompile=False)
  File "C:\Users\*****\AppData\Roaming\Python\Python37\site-packages\tvm-0.5.dev0-py3.7-win-amd64.egg\tvm\module.py", line 128, in export_library
    fcompile(file_name, files, **kwargs)
  File "C:\Users\*****\AppData\Roaming\Python\Python37\site-packages\tvm-0.5.dev0-py3.7-win-amd64.egg\tvm\contrib\cc.py", line 35, in create_shared
    _windows_shared(output, objects, options)
  File "C:\Users\*****\AppData\Roaming\Python\Python37\site-packages\tvm-0.5.dev0-py3.7-win-amd64.egg\tvm\contrib\cc.py", line 120, in _windows_shared
    raise RuntimeError(msg)
RuntimeError: Compilation error:
Microsoft (R) Incremental Linker Version 14.16.27026.1
Copyright (C) Microsoft Corporation.  All rights reserved.

lib.o : fatal error LNK1143: invalid or corrupt file: no symbol for COMDAT section 0x5
```

**Comment by tqchen** [comment]
Please open a new thread in https://discuss.tvm.ai/

**Comment by mnboos** [comment]
I was able to export the library.

I'm not 100% sure I correctly understand what happened. As far as I know, it's a bad idea to mix different compilers. And since I used the llvm target, the export fails because it uses the MSVC compiler, instead of LLVM. The same goes for the linking.

So the solution was:
1. Update `tvm/contrib/cc.py` as follows:
```
--- a/cc.py
+++ b/cc_updated.py
@@ -59,7 +59,7 @@ def _linux_shared(output, objects, options, cc="g++"):
 
 
 def _windows_shared(output, objects, options):
-    cl_cmd = ["cl"]
+    cl_cmd = [r"C:\Program Files\LLVM\bin\clang-cl"]
     cl_cmd += ["-c"]
     if isinstance(objects, str):
         objects = [objects]
@@ -79,7 +79,7 @@ BOOL APIENTRY DllMain( HMODULE hModule,\
     cl_cmd += [dllmain_path]
 
     temp_path = dllmain_path.replace("dllmain.cc", "")
-    cl_cmd += ["-Fo:" + temp_path]
+    cl_cmd += ["-Fo" + temp_path]
     try:
         proc = subprocess.Popen(
             cl_cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
@@ -91,7 +91,7 @@ BOOL APIENTRY DllMain( HMODULE hModule,\
         msg = "Compilation error:\n"
         msg += py_str(out)
         raise RuntimeError(msg)
-    link_cmd = ["link"]
+    link_cmd = [r"C:\Program Files\LLVM\bin\lld-link"]
     link_cmd += ["-dll", "-FORCE:MULTIPLE"]
 
     for obj in objects:
```
2. Run in Visual Studio Command Prompt to make sure all the required libraries are found.

**Comment by mnboos** [comment]
I would consider that a workaround for an unsolved problem, not a solution. With the patch above it's possible to make `export_library` work on windows. Maybe an expert could comment my approach @tqchen ?

**Comment by mnboos** [comment]
@myproject24 Did you run the script in the Visual Studio Command Prompt?

**Comment by chinakook** [comment]
It cannot export_library in windows at all because *.o cannot be compiled by cl.exe at all.

**Comment by mnboos** [comment]
Did you read my comment above that describes how to solve this problem?

**Comment by myproject24** [comment]
@mnboos I have built LLVM and TVM using Visual studio command Prompt build was success and i got all libraries, based this tvm build document https://docs.tvm.ai/install/from_source.html 

Building on Windows

TVM support build via MSVC using cmake. The minimum required VS version is Visual Studio Community 2015 Update 3. In order to generate the VS solution file using cmake, make sure you have a recent version of cmake added to your path and then from the tvm directory:

mkdir build
cd build
cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_BUILD_TYPE=Release -DCMAKE_CONFIGURATION_TYPES="Release" ..

This will generate the VS project using the MSVC 14 64 bit generator. Open the .sln file in the build directory and build with Visual Studio. In order to build with LLVM in windows, you will need to build LLVM from source. You need to run build the nnvm by running the same script under the nnvm folder.

    Install tvm python bindings by setup.py:

    # install tvm package for the current user
    # NOTE: if you installed python via homebrew, --user is not needed during installaiton
    #       it will be automatically installed to your user directory.
    #       providing --user flag may trigger error during installation in such case.
    export MACOSX_DEPLOYMENT_TARGET=10.9  # This is required for mac to avoid symbol conflicts with libstdc++
    cd python; python setup.py install --user; cd ..
    cd topi/python; python setup.py install --user; cd ../..
    cd nnvm/python; python setup.py install --user; cd ../..

Python dependencies

        Necessary dependencies:

    pip install --user numpy decorator

        If you want to use RPC Tracker

    pip install --user tornado

        If you want to use auto-tuning module

    pip install --user tornado psutil xgboost

after doing all steps successfully i tried to run tvm sample programs from https://docs.tvm.ai/tutorials/frontend/from_onnx.html#sphx-glr-tutorials-frontend-from-onnx-py this works fine.
But model converstion is problem that tvm tutorial https://docs.tvm.ai/tutorials/nnvm_quick_start.html#sphx-glr-tutorials-nnvm-quick-start-py Save and Load Compiled Module is failing.

**Comment by zaidao2023** [comment]
can you fix this problem?

**Comment by mnboos** [comment]
It worked for me after patching TVM with the patch I showed above. After some testing I reduced it to the following:

```
diff --git a/python/tvm/contrib/cc.py b/python/tvm/contrib/cc.py
index 0ffa6c42..906bf4cc 100644
--- a/python/tvm/contrib/cc.py
+++ b/python/tvm/contrib/cc.py
@@ -91,7 +91,7 @@ BOOL APIENTRY DllMain( HMODULE hModule,\
         msg = "Compilation error:\n"
         msg += py_str(out)
         raise RuntimeError(msg)
-    link_cmd = ["link"]
+    link_cmd = ["lld-link"]
     link_cmd += ["-dll", "-FORCE:MULTIPLE"]

     for obj in objects:
```

Apply it:
```
set PATH=%path%;C:\Program Files\Git\bin
bash.exe -c 'patch -p1 ~/AppData/Roaming/Python/Python37/site-packages/tvm-0.5.dev0-py3.7-win-amd64.egg/tvm/contrib/cc.py cc.py.patch'
```

**Comment by zaidao2023** [comment]
thanks

**Comment by tqchen** [comment]
@mnboos Do you mind send a patch ?

**Comment by mnboos** [comment]
@tqchen Do you mean as PR?

**Comment by tqchen** [comment]
Yes please

**Comment by mnboos** [comment]
Okay done. 

See: https://github.com/dmlc/tvm/pull/2713

**Comment by chinakook** [comment]
LGTM.
