### ISSUE TITLE
wrong elf class elfclass64

### ISSUE THREAD

**Issue by 2909638069** [dmlc/tvm#2458]
I compile at 64bit, deploy at 32bit.
The lib.so occurs error when tvm.module.load at 32bit.
It appears that I should compile at 32bit machine, however I have no one.
What can I do?

**Comment by denis0x0D** [comment]
You can compile 32 bit library on 64 bit host,
It's preety much straightforward.
You need to have:
1. gcc-multilib package, because you need 32 bit crt*.o files, otherwise you can rebuild gcc from source adding --enable-multilib to configure file.
2. llvm 32bit, you can rebuild llvm from source adding -m32 to CXXFLAG
https://clang.llvm.org/get_started.html
export CFLAGS='-m32'
export CXXFLAGS='-m32'
3. rebuild tvm
export CFLAGS='-m32'
export CXXFLAGS='-m32'
cmake -DUSE_LLVM=/path/to_32bit/llvm-config ..
make
4. verify build
readelf -h libtvm.so

**Comment by DanGrizzly** [comment]
It's not straightforward, nor does it work. Tried this myself because we had the same issue. After many issues with dependencies and libraries needed for a 32bit build, even if the build is successful one cannot run tvmc or any python scripts using the tvm library ("WRONG ELFCLASS32" error).
