### ISSUE TITLE
[RFC][Relay] Implicit type casting vs explicit dtype conversion

### ISSUE THREAD

**Issue by icemelon9** [dmlc/tvm#2659]
I found two issues in inferring the output dtype of Relay's type inference.
- For some unary operations such as `sqrt`, `log`, `exp`, the type inference directly uses the input dtype as output dtype. However, if the input type is int type, this inference fails.
- All binary operations now enforeces both operands have the same dtype. However, it is possible that a float tensor adds a int tensor. But it is not allowed in Relay. Though one can argue this is a good language feature for strict type constraint, imported models from existing frameworks could generate such operations.

I suggest two changes to the current type inference in Relay.
- For unary ops like `sqrt`, `log`, `exp`, don't specify the output dtype. Instead only provide a hint that the output could be a float type. Let the subsequent ops specify whether the output dtype is `float32`, `float64`, `float16`, etc.
- To solve the second issue, there are two options. (I prefer the first option as it is more systemical.)
  - Disable the enforcement that both operands have the same dtype. Implicit cast the dtype for the output dtype. Notice that, implicit cast also exists in the HalideIR.
  - Check the dtype in Relay's frontend converter, and cast the operand's dtype whenever they're different.

**Comment by Ravenwater** [comment]
That feels very ad hoc. With type conversions you need to work out the type hierarchy otherwise you will quickly end up with computational errors that are impossible to debug. Languages will demand that if a conversion is semantically important it needs to be specified. Otherwise you quickly end up with float64 that capture a default progression, but which will be very inefficiënt.

History tells us that you can't take the short cut, it will bite you. So my two cents is to make the conversion an explicit operator so that the modeler has the control they need. It will also prepare the model for new number systems such as bfloat8, posits, and others yet to be discovered.

**Comment by tqchen** [comment]
The current IR semantics requires explicit conversion of dtype, which works OK in most cases. I think it might be good to keep it that way

**Comment by zhiics** [comment]
I think it might be too strict to assert the types in relation. I understand that making type conversion implicit might bring some burdens in debugging. But it looks to me that providing type hint and leveraging the type solver or having some specific passes to solve determine the type should be a good option.

**Comment by tqchen** [comment]
I agree there are tradeoffs that need to be made. This is like the same trade-off we have to make when thinking about broadcasting in binary operators. Let us list the pros and cons

**Pros of Implicit Casting**
- it makes frontend building relatively easy when dealing with mixed-dtype code

**Pros of Explicit Casting**

- Mixed dtype is relatively rare in deep learning, so one can argue explicit casting is fine.
- It makes support user-defined new floating type easy(e.g. bfloat), which is crucial for accelerators.
- It simplifies the codegen support in the IR

**Comment by junrushao1994** [comment]
So is there any other benefit of bringing in implicit conversion, apart from making it easier to write frontend converters?

On the other hand, could we provide the flexibility of building a temporary Relay IR with non-strict dtypes, and then add a pass to insert explicit conversion?

**Comment by Ravenwater** [comment]
In modern languages like Golang, the implicit cast has been removed. The rational being that through the decades of sw engineering practice implicit casts have caused more grief than provided in convenience. Secondly, the observation that sw code is read many time more than it is written also points to using explicit casts, so that all the information is present in the code being read.

In numerical software, explicit casting is used to implement numerical adapters (re-discretization, float/integer, and encoding conversion), and for high-performance and OS/driver software to access very specific attributes of the number (the frexp functions). The numerical adapter use case is readily present in DL.

Implicit casting requires that you design a type hierarchy with associated conversion rules. However, even simple languages like C have shown that these type hierarchies are difficult to make consistent. With user-defined types, your type hierarchy is unlikely to be complete and/or consistent, and thus you'll create backward compatibility nightmares that will make your implicit casting code not maintainable.  

So, there really isn't a good reason to implement implicit casting in any way, shape, or form.

**Comment by tqchen** [comment]
@icemelon9  can we conclude and summarize the discussions?

**Comment by tqchen** [comment]
I  guess the conclusion, for now, is to keep things as it is and use explicit casting

**Comment by icemelon9** [comment]
Yes, I agree that we should just keep the explicit casting.
