### ISSUE TITLE
[Relay][Discussion] What to do about Partial Pattern Matching in Relay?

### ISSUE THREAD

**Issue by MarisaKirisame** [dmlc/tvm#2815]
Relay pattern matching allow partial pattern - that is, some ADT might not be covered by the match.

Originally, we do not put much thought into it - relay throw a runtime error (in C++) if it come up, as we do not expect it to be used.

However, as of #2771 , function defined by partial pattern matching is entering the standard library (prelude).

We should provide a check to see if a pattern might be partial (some case undefined), and have the check on by default, to guard against programmer error.

But beside this, we still has two design choice to make:

0: How to let user annotate partial match? (add a boolean field to match, or (force all match to be total, but add some error mechanism in relay, so user can write partial match by erroring in the unhandle case. it can be made easier to program with syntax sugar)
1: What kind of error for unhandled case? (internal error as of right now, adding an exception mechanism to relay)

All choice seems fine to me, so I wanna hear some opinion.

**Comment by wweic** [comment]
For item 1, I'd like to have exception in Relay as you said. Instead of crashing interpreter/VM(internal error), user should got an exception from interpreter/VM, meanwhile interpreter/VM stays healthy. 

For item 0, do we need to have special syntax for partial match? Right now Relay accepts partial program, maybe just add proper warning message when we compile Relay program(for VM) or eval Relay program(for interpreter)?

**Comment by MarisaKirisame** [comment]
Warning is acceptable, but it mean everytime prelude load it will generate warning unless turn offed.
Special syntax is not that hard, we can just have one called pmatch. The noise is minimal (or rather, I would say this is instructive, as it is very easy to see whether a match is partial or not)

**Comment by wweic** [comment]
If we agree to add exception in Relay, user can throw exception for clauses that aren't expected to match to avoid warning. Then we won't need `pmatch`. In general we should avoid partial match and alert our user of potential runtime exception, instead of suppressing the the warning. What do you think?

**Comment by MarisaKirisame** [comment]
@wweic sounds good to me. @jroesch (private communication) dont want exception because it cause complication (IR, VM, concurrency, etc), and argue we should panic right now. I agree at this point. I think I will implement a checker, warn/error(both are pretty fine) for partial match, and provide C++/python library function for adding the default case.

**Comment by wweic** [comment]
Sounds good to me. When we need exception, we just swap the panic logic with throwing an exception.

**Comment by tqchen** [comment]
Close due to inactive status, further discussions are welcomed in http://discuss.tvm.ai/ under development category
