### ISSUE TITLE
[Relay][RFC] VM Object and Intepreter value

### ISSUE THREAD

**Issue by wweic** [dmlc/tvm#3209]
Currently we can not convert VM data type object to interpreter `ConstructorValueNode`:
https://github.com/dmlc/tvm/blob/78a0f47b7e823aecea693c1be7a2ff7523b3b09e/src/relay/backend/vm/vm.cc#L73-L83

It's because right now we don't have serialization support for `tag_index_map` in `compiler.cc`. We need to design a protocol to serialize `Constructor` so we can save the map to file in vm compiler, then load it in vm runtime. 

cc: @zhiics @jroesch @MarisaKirisame @slyubomirsky @tqchen @icemelon9

**Comment by MarisaKirisame** [comment]
We do not has to seralize constrcutor. There is a tag and the match system only use the tag to do pattern matching. Just serialize the tag which is an int of some type (probably size_t) and you are done.

**Comment by wweic** [comment]
@MarisaKirisame It's not an issue if the object is only manipulated inside vm. this function I pasted is to converter vm object into interpreter `ConstructorValueNode`. And to construct `ConstructorValueNode`, it requires `Constructor`:
https://github.com/dmlc/tvm/blob/78a0f47b7e823aecea693c1be7a2ff7523b3b09e/include/tvm/relay/interpreter.h#L185-L187

And `Constructor` is more than an int tag. it also has the name, type, fields etc.

**Comment by MarisaKirisame** [comment]
@wweic what happend if you make a new Constructor, with the int tag, and all other field as null? I put the int tag there because it bypass pointer equality issues, and is just more efficient. To the best of my knowledge, all code only use and should only use that int tag, unless it is user-interfacing.
If you insist on having the full constructor, It can still be done by using the original type - it will be a TypeCall of a DataType, and that DataType has Constructor. Just use the tag to read the correct constructor.

**Comment by tqchen** [comment]
I personally think it is a good design to have a clear separation between runtime and interpreter. Even more specifically, I think we should try to unify the objects so that the interpreter also returns objects(with some special instance of opaque objects that might contain interpreter specific values

**Comment by jroesch** [comment]
The problem with unification of the values is that closures fundamentally have a different representation and can't use the runtime's because they must store a NodeRef (i.e the code).

**Comment by tqchen** [comment]
That is why I mean we might need to have an extensible Object for closure, with an opaque ctx pointer that could point to the NodeRef(code), and possibly a function pointer that defines the calling behavior.

**Comment by slyubomirsky** [comment]
I am very much in favor of changing the representation of `ConstructorValue`, as having to keep the module around (to ensure pointer equality) caused me a bit of pain in my Relay to Python compiler PR.

**Comment by icemelon9** [comment]
I'm working on a PR that separates VM Object from Interpreter value #3391. After the PR, VM will directly return Object to python instead of converting to Interpreter Value. Currently I haven't dealt with `ClosureObject` since it won't appear in the return value.

**Comment by tqchen** [comment]
https://github.com/dmlc/tvm/pull/3391
