### ISSUE TITLE
features.md is missing

### ISSUE THREAD

**Issue by yongwww** [dmlc/tvm#3691]
https://github.com/dmlc/tvm/blob/cffb4fba03ea582417e2630bd163bca773756af6/python/tvm/autotvm/feature.py#L74

**Comment by cchung100m** [comment]
Hi @merrymercy @tqchen 

This issue has been posted on [Discuss Forum](https://discuss.tvm.ai/t/features-md-missing/3086) and here, I'm interested in working on this if no one else has signed up. Can you please point me how to solve it because I cannot find the similar file which talking about axis in the IR under doc/ directory. 

Many thanks,

**Comment by merrymercy** [comment]
replied at the forum
