### ISSUE TITLE
Docker build failing with nnpack depreciation error

### ISSUE THREAD

**Issue by lhutton1** [dmlc/tvm#4086]
I've recently just tried to build tvm using the docker image provided in the repo. I'm getting the following depreciation errors when trying to build with nnpack enabled:

```[ 12%] Building CXX object CMakeFiles/tvm_runtime.dir/src/contrib/nnpack/convolution.cc.o
In file included from /NNPACK/build/include/nnpack.h:7:0,
                 from /workspace/src/contrib/nnpack/fully_connected.cc:27:
/NNPACK/build/include/pthreadpool.h:185:14: error: 'pthreadpool_function_1d_t' is deprecated [-Werror=deprecated-declarations]
  size_t range);

[more depreciation warnings....]

cc1plus: all warnings being treated as errors
CMakeFiles/tvm_runtime.dir/build.make:758: recipe for target 'CMakeFiles/tvm_runtime.dir/src/contrib/nnpack/nnpack_utils.cc.o' failed
make[4]: *** [CMakeFiles/tvm_runtime.dir/src/contrib/nnpack/nnpack_utils.cc.o] Error 1
```

**Comment by mshawcroft** [comment]
Confirmed. The version of nnpack pulled and built by tvm is pinned. However it appears that nnpack itself clones the pthreadpool project and checks out the most recent master of that project.  Ideally we should have a way of properly pinning nnpack *and* it's dependent packages in order to have a stable  build environment for tvm.

**Comment by tqchen** [comment]
should be resolved by https://github.com/dmlc/tvm/pull/4152 thanks for reporting the problem
