### ISSUE TITLE
what about the support for third-part accelerators?

### ISSUE THREAD

**Issue by meiniangpp** [dmlc/tvm#4110]
Hi, it's a very impresive tool. And I have 2 questions.
1. As for the auto-tuning, is it tunning the structure of the dnn, or tunning the scheduling and/or compiling on the target platform?
2. Does it support for third-part accelerators? Such as some TPU like accelerators of our own?

Thank you a lot for your time!

**Comment by comaniac** [comment]
Hi, for your questions:

1. The AutoTVM is for performance tuning. It tunes scheduling for each operators in the network as well as the graph level data layout for the given platform. The architecture tuning, which refers to neural architecture search, is not supported yet in the current TVM.

2. TVM currently does not really support third party accelerators but we do have an ongoing plan for it.

p.s. it’s suggested to post general questions like these to the discussion forum (discuss.tvm.ai) instead of GitHub issue.
