### ISSUE TITLE
conv2d schedule for cuda works wrong for some filter sizes

### ISSUE THREAD

**Issue by notorca** [dmlc/tvm#668]
With flag values in [512,768] computations are not spited and generated kernel have too big threadgroup shared input. Reproduced on convolution with input (1, 256, 13, 13) and kernel (512, 256, 3, 3)

**Comment by tqchen** [comment]
@Laurawly can you look into this?

**Comment by Laurawly** [comment]
@notorca I've tried running verify_conv2d_nchw(1, 256, 13, 512, 3, 1, 1)
    verify_conv2d_nchw(1, 256, 13, 512, 3, 1, 0) in https://github.com/dmlc/tvm/blob/master/topi/tests/python/test_topi_conv2d_nchw.py and both cases work fine on K80 GPU. Could you provide the cases which don't work for you? Thanks!

**Comment by notorca** [comment]
My bad, I described the problem in wrong way. Problem is not in incorrect calculations. I'm running code produced by tvm with 'metal' target on iOS. And for some input kernel sizes it fails in runtime, because metal can't allocate enough shared memory. And looks like it is related to the gap in conditions here https://github.com/dmlc/tvm/blob/master/topi/python/topi/cuda/conv2d_nchw.py#L437 for flag values in [512,768]. In my tests
```
verify_conv2d_nchw(1, 256, 13, 512, 3, 1, 1) # flag=768, can't be calculated
verify_conv2d_nchw(1, 128, 13, 512, 3, 1, 1)  # flag=640, can't be calculated
verify_conv2d_nchw(1, 512, 13, 512, 3, 1, 1)  # flag=1024, can be calculated
```
I've added `print(tvm.lower(s1, [A, W, B], simple_mode=True))` line to the test, to check generated pseudocode, add looks like problem in the first two cases is in this allocation:
```
  // attr [W.shared] storage_scope = "shared"
  allocate W.shared[float32 * 4672]
```
While in third case: 
```
  // attr [W.shared] storage_scope = "shared"
  allocate W.shared[float32 * 1168]
```
[log.txt](https://github.com/dmlc/tvm/files/1514557/log.txt)
Is there any way to control amount of the cache memory allocated in the schedule to avoid such problem?

**Comment by Laurawly** [comment]
@notorca Thanks for the clarification! I see, so the problem is related to hardware. I tried to reduce the number of threads (num_thread_x) here: https://github.com/dmlc/tvm/blob/master/topi/python/topi/cuda/conv2d_nchw.py#L250
And when it's changed to 8 instead of 64 (https://github.com/dmlc/tvm/blob/master/topi/python/topi/cuda/conv2d_nchw.py#L255) or 16 (https://github.com/dmlc/tvm/blob/master/topi/python/topi/cuda/conv2d_nchw.py#L298), W.shared becomes [float32 * 584]. 
@tqchen Maybe we should use parameters specific to hardware just like "tvm.target.current_target(allow_none=False).max_num_threads"?

**Comment by tqchen** [comment]
Sorry for the delayed I think we could try to set max_num_thread as optional target parameter, like with tvm.target.cuda(max_num_threads=10). PR is welcomed
