### ISSUE TITLE
[SCHEDULE] New Reduction Mode for Tensorize

### ISSUE THREAD

**Issue by tqchen** [dmlc/tvm#714]
So far we are implementing reduction as 

```python

init(C)

for rx in reduce_range_x:
    for ry in reduce_range_y:
      update(C, reduce_value)
``` 

This may not be desirable, especially when there is no reset(init) intrinsic available. So alternatively, we can do 

```python
for rx in reduce_range_x:
    for ry in reduce_range_y:
      if likely(rx == 0) and likely(ry == 0):
         compute(C, reduce_value)
      else:
         update(C, reduce_value)
``` 

The subsequent loop split process will peel the loop to remove the likely condition when possible.

For now, we can enable this mode, when user did not provide init intrinsic in ```tensor_intrin```, but provided compute and update intrinsic

**Comment by tqchen** [comment]
cc @derisavi-huawei @merrymercy let me know if it makes sense to you and see if any of you are interested in this

**Comment by derisavi-huawei** [comment]
I'm not crystal clear on what the problem is. Is this about an alternative way for TVM to generate IR for `reduce_axis`, or is it about what kind of patterns (init/update vs compute/update) tensorize can match, or both, or something else?  That was a lot of ORs :-) Can you please elaborate?

Also, I don't clearly see the pros and cons of the design decisions involved here. Could you give us initial ideas so we can brainstorm?

In terms of interest, it's not something that will be on our radar in the next month or so. If we grow an interest in it, I'll definitely let you know.

Sorry! You were expecting answers and you received many questions instead :-)

**Comment by tqchen** [comment]
It is related to https://github.com/dmlc/tvm/issues/512 on comment in terms of the alternative way of generating reduction, and is useful when init intrinsic is not available due too limitation of hardware

**Comment by merrymercy** [comment]
I can try this but may not too soon.

**Comment by derisavi-huawei** [comment]
Second form makes life easier for us, so we are interested. Unfortunately we can't invest time in this in the short term.

**Comment by taknevski** [comment]
Hi,
Let me know if this is off-topic..
I was wondering if  the reduction initialization could be scheduled separately much in the same way as the tvm.scan init and update operations. Currently I want to move the zero initialization for the output tensor in convolution to a separate loop nest(at the outermost level) but I can't seem to find a way to do it easily.

**Comment by kun-zh** [comment]
@tqchen , I have a solution in my local now, as we discussed, firstly set the reset part as "None" in intrinsic definition, then transform the update part in tensorize.cc. I will send to u for review after some tests.

**Comment by kun-zh** [comment]
@tqchen , I created a pull request, can u help to review it?

**Comment by tqchen** [comment]
https://github.com/dmlc/tvm/pull/727

**Comment by tqchen** [comment]
close this, thanks to @kun-zh
