### ISSUE TITLE
A TVM Backend for Highly Optimized (GPU) Assembly Directly?

### ISSUE THREAD

**Issue by guopinglong** [dmlc/tvm#752]
Hi,
  One issue of TVM right now is the schedule. We need high quality schedules not just for more workloads, but also for current supported ones with extreme performance demands. Many NN workloads can be transformed into a dataflow graph of basic, sometimes "approximate" GEMM/Conv blocks. However, some low level optimizations (such as those related to register allocation, instruction scheduling, etc) are not naturally available through high level transformations. One possible approach to this issue is a backend targeted directly for highly optimized assembly generation. One excellent example closely related to this is the neon project, with a set of highly optimized SASS kernels for Maxwell/Pascal architectures.
I am curious how people in the TVM community view this issue. I believe a NN compiler with extreme code generation capability across multiple platforms will be of enormous value to the community.
Thanks.

**Comment by xqdan** [comment]
Tvm do have a backend in which target related intrinsics are emited in llvm IR and fed to llvm right away. because abstraction of tvm is higher than traditional compiler like gcc/llvm, so it would be easier for tvm to generate instructions like vector or matrix, that is to say, tvm can offload some difficult work from  traditional compiler and no need to do low level optimizations itself but just use them directly.
