### ISSUE TITLE
[DOCS] Tutorials for TOPI

### ISSUE THREAD

**Issue by tqchen** [dmlc/tvm#917]
TOPI library is a numpy-like abstraction build on top of TVM's core language. So far we have benefit a lot from it, but there is yet a tutorial about it. This issue calls for contribution for such tutorial

**Comment by tqchen** [comment]
@sxjscience are you interested in making one?

**Comment by ehsanmok** [comment]
@tqchen I'm interested in writing a tutorial on time as I'm learning it, if no one else is currently working on it!

**Comment by ehsanmok** [comment]
@tqchen so I just started writing the tutorial and there're some points needs clarification:
1) Should I put it in tutorials/topi/ or in tutorials/language?
2) How much should I go into topi package? since this is an introduction, for example, should I talk about topi/vision or nn it's enough to introduce its advantages and write separate tutorials for vision and nn?

**Comment by tqchen** [comment]
Let us put in tutrials topi, you can use your judgment on 2. I think it makes sense to have multiple tutorials

**Comment by tqchen** [comment]
cc @sxjscience

**Comment by ehsanmok** [comment]
Alright! so I'll try to make it simple and will send it soon.

**Comment by tqchen** [comment]
https://github.com/dmlc/tvm/pull/1222
