### ISSUE TITLE
cache_write/compute_inline on op with multiple outputs

### ISSUE THREAD

**Issue by DengLLy** [dmlc/tvm#928]
For some case like argmax, we use one compute to output to two tensors (just like the way topi.argmax does). However, cache_write/compute_inline only accept tensor.op with one output.

**Comment by tqchen** [comment]
This is a restriction on the language, maybe we should have more clear error messages. They are not supported because we do not yet have semantics for these operations.

If we have a proposal on the expected semantics in a new issue, and provide examples, we can enhance the language to make it happen
