### ISSUE TITLE
About loading precompiled nnvm library

### ISSUE THREAD

**Issue by iihihiuh** [dmlc/tvm#954]
I successfully built metal interface on Xcode, but when I was loading lib.so file and parameters file so that I could deploy on iPhone. However, I cannot open lib.so file.
An error has occurred:
<img width="1012" alt="screen shot 2018-03-02 at 10 48 02" src="https://user-images.githubusercontent.com/35404098/36915940-4d0d13ba-1e07-11e8-9ac6-42696fc04b3f.png">

How could I resolve this issue?

**Comment by tqchen** [comment]
It seems that you tried to directly load the metal module(with suffix metal) from the bundle, and it opens a json file, which is the network def, instead of the metadata.

Try to reference https://github.com/dmlc/tvm/blob/master/apps/ios_rpc/tests/ios_rpc_test.py#L45 which is good until this point, that will give you a ```library.dylib```.

To load the dylib or so file, do not use MetalModule, instead, use DSOModule load or simply Module::LoadFromFile

**Comment by iihihiuh** [comment]
Thank you!

**Comment by iihihiuh** [comment]
@tqchen Actually, the "so" file I am trying to load is a nnvm compiled library(which is already a dynamic library not but built by tvm so far). I do not how to get "tvm schedule" (  s = tvm.create_schedule(B.op)) from nnvm module I saved (module = graph_runtime.create(deploy_graph, lib, tvm.gpu(0))).

**Comment by tqchen** [comment]
Same thing goes for nnvm compiled library. NNVM will give you a lib, which is a module that you should be able to use the same export_library to export

**Comment by tqchen** [comment]
close due to inactivity. Hopefully last answer resolved your question, feel free to reopen or open another issue for followups
