### ISSUE TITLE
uint8, int8, uint16, int16, uint64 unsupported for device function arguments

### ISSUE THREAD

**Issue by cnuernber** [dmlc/tvm#984]
So that leaves:

uint32, int32, float*, int64 as the supported argument types for device functions :-).

**Comment by tqchen** [comment]
true, some of those are due to the limitation of the certain device API. Others are simply assumptions to support common arguments. It is not a big technical issue, but rather to simplify the project and calling a convention. If there is any reason we want more POD argument type, we can add them. But for now we find they are quite sufficient

**Comment by cnuernber** [comment]
Agreed, just noting it here.
