### ISSUE TITLE
[question] choice of Barrier impl

### ISSUE THREAD

**Issue by nhynes** [dmlc/tvm#988]
In [`TVMBackendParallelBarrier`](https://github.com/dmlc/tvm/blob/master/src/runtime/thread_pool.cc#L403), is there any reason why this particular implementation is used instead of the more "standard" one which uses a mutex+cond_var?

**Comment by tqchen** [comment]
The barrier was used by multiple threads to prevent one thread from running too fast (and flush the common L2 cache of another one). This happens when all the threads are doing their works and it is desirable to have a busy spinning strategy than mutex which traps into OS. 

In most cases, the introduction of barrier only brings small improvement so it is OK to leave the implementation empty, and correctness won't get hurt

**Comment by nhynes** [comment]
A most informative answer. Thanks very much!
